{% set version = "1.0.5.dev0" %}
{% set python_min = "3.10" %}
{% set build = 0 %}

package:
  name: bacoli-py
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  string: {{ target_platform | replace('-', '_') }}_py{{ python | replace('.', '') }}_{{ build }}

requirements:
  build:
    - python ={{ python_min }}
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # for Linux; on macOS, this will map to gfortran
  host:
    - python ={{ python_min }}
    - pip
    - setuptools <60
    - numpy <2
    - libgfortran
  run:
    - python ={{ python_min }}
    - numpy <2
    - libgfortran

test:
  imports:
    - bacoli_py

about:
  home: https://github.com/mrclary/bacoli_py
  description: |
    bacoli_py is a Python package for solving systems of 1D Parabolic
    Partial Differential Equations.
