name: build
channels:
  - conda-forge
dependencies:
  - anaconda-client  # uploading to Anaconda
  - conda-build      # building the conda package
  - gfortran         # compiling the fortran code
  - meson-python     # build backend
  - numpy >=2        # f2py, meson backend
  - python
