name: Build wheels for bacoli-py

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-wheels:
    name: ${{ matrix.os }} - Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      DISTDIR: ${{ github.workspace }}/dist
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10']
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/build-environment.yml
          extra-specs: |
            python=${{ matrix.python_version }}
            sel(osx): delocate
            sel(win): delvewheel
            sel(linux): auditwheel<5.2.0

      - name: Update Environment
        run: |
          if [[ $RUNNER_OS = 'macOS' ]]; then
              echo 'Linking gfortran...'
              ln -s /usr/local/bin/gfortran-15 /usr/local/bin/gfortran
          fi

      - name: Show Environment
        run: |
          micromamba info
          micromamba list
          gfortran --version

      - name: Build Wheel
        run: |
          python -m pip wheel -v -w $DISTDIR .
          WHEEL=$(find $DISTDIR -name bacoli*.whl)
          echo "WHEEL=$WHEEL" >> $GITHUB_ENV
          echo "NAME=$(basename $WHEEL)" >> $GITHUB_ENV

      - name: Delocate Wheel
        run: |
          zipinfo $WHEEL
          echo ''
          if [[ $RUNNER_OS = 'macOS' ]]; then
              delocate-listdeps --all $WHEEL
              delocate-wheel -v $WHEEL
              delocate-listdeps --all $WHEEL
          fi
          if [[ $RUNNER_OS = 'Windows' ]]; then
              opts=("--add-path" "build/lib.win*/bacoli_interface/.libs")
              delvewheel show ${opts[@]} $WHEEL
              delvewheel repair -v ${opts[@]} -w $DISTDIR $WHEEL
              delvewheel show ${opts[@]} $WHEEL
          fi
          if [[ $RUNNER_OS = 'Linux' ]]; then
              auditwheel show $WHEEL
              auditwheel repair -w $DISTDIR --plat linux_x86_64 $WHEEL
              auditwheel show $WHEEL
          fi
          echo ''
          zipinfo $WHEEL

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.WHEEL }}
          name: ${{ env.NAME }}

      - name: Get Release
        if: github.event_name == 'release'
        id: get_release
        uses: bruceadams/get-release@v1.2.0

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.WHEEL }}
          asset_name: ${{ env.NAME }}
          asset_content_type: application/zip
